config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :departamentos
  resources :cargos
  resources :abafuncionarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/abafuncionario.rb
class Abafuncionario < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cargo.rb
class Cargo < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abafuncionarios_controller.rb
class AbafuncionariosController < ApplicationController
  before_action :set_abafuncionario, only: %i[ show edit update destroy ]

  # GET /abafuncionarios or /abafuncionarios.json
  def index
    @abafuncionarios = Abafuncionario.all
  end

  # GET /abafuncionarios/1 or /abafuncionarios/1.json
  def show
  end

  # GET /abafuncionarios/new
  def new
    @abafuncionario = Abafuncionario.new
  end

  # GET /abafuncionarios/1/edit
  def edit
  end

  # POST /abafuncionarios or /abafuncionarios.json
  def create
    @abafuncionario = Abafuncionario.new(abafuncionario_params)

    respond_to do |format|
      if @abafuncionario.save
        format.html { redirect_to abafuncionario_url(@abafuncionario), notice: "Abafuncionario was successfully created." }
        format.json { render :show, status: :created, location: @abafuncionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @abafuncionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abafuncionarios/1 or /abafuncionarios/1.json
  def update
    respond_to do |format|
      if @abafuncionario.update(abafuncionario_params)
        format.html { redirect_to abafuncionario_url(@abafuncionario), notice: "Cadastro de funciário atualizado" }
        format.json { render :show, status: :ok, location: @abafuncionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @abafuncionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abafuncionarios/1 or /abafuncionarios/1.json
  def destroy
    @abafuncionario.destroy!

    respond_to do |format|
      format.html { redirect_to abafuncionarios_url, notice: "Cadastro de funcionario excluido" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abafuncionario
      @abafuncionario = Abafuncionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def abafuncionario_params
      params.require(:abafuncionario).permit(:nomecompleto, :datanasc, :genero, :cpf, :rg, :rua, :numero, :complemento, :bairro, :cidade, :estado, :cep, :telefone, :email, :cargo, :status, :departamento)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern  
    protected
    def after_sign_in_path_for(resource)
      '/direcao.html' # Caminho para a página HTML na pasta public
  
    end
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[ show edit update destroy ]

  # GET /cargos or /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1 or /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos or /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to cargo_url(@cargo), notice: "Cadastro do cargo criado " }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1 or /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to cargo_url(@cargo), notice: "Cargo foi atualizado" }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1 or /cargos/1.json
  def destroy
    @cargo.destroy!

    respond_to do |format|
      format.html { redirect_to cargos_url, notice: "O cadastro deste cargo foi excluido" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:nomecargo, :descricao, :departamento, :nivelcargo, :salbase, :requisitos, :beneficios, :statuscargo)
    end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamento_url(@departamento), notice: "Cadadastro de departamento criado" }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Cadastro de departamento editado" }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy!

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Cadastro de departamento excluido" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nomedepartamento, :descricao, :codigodep, :localizacao, :string, :statusdep)
    end
end

app/helpers/abafuncionarios_helper.rb
module AbafuncionariosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/abafuncionarios/_abafuncionario.html.erb
<div id="<%= dom_id abafuncionario %>">
  <p>
    <strong>Nomecompleto:</strong>
    <%= abafuncionario.nomecompleto %>
  </p>

  <p>
    <strong>Datanasc:</strong>
    <%= abafuncionario.datanasc %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= abafuncionario.genero %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= abafuncionario.cpf %>
  </p>

  <p>
    <strong>Rg:</strong>
    <%= abafuncionario.rg %>
  </p>

  <p>
    <strong>Rua:</strong>
    <%= abafuncionario.rua %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= abafuncionario.numero %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= abafuncionario.complemento %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= abafuncionario.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= abafuncionario.cidade %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= abafuncionario.estado %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= abafuncionario.cep %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= abafuncionario.telefone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= abafuncionario.email %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= abafuncionario.cargo %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= abafuncionario.status %>
  </p>

  <p>
    <strong>Departamento:</strong>
    <%= abafuncionario.departamento %>
  </p>

</div>

app/views/abafuncionarios/_form.html.erb
<%= form_with(model: abafuncionario) do |form| %>

  <% if abafuncionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(abafuncionario.errors.count, "error") %> proibiu que este funcionário fosse cadastrado:</h2>

      <ul>
        <% abafuncionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<body>

  <div>
    <%= form.label :nomecompleto, style: "display: block" %>
    <%= form.text_field :nomecompleto %>
  </div>

  <div>
    <%= form.label :datanasc, style: "display: block" %>
    <%= form.date_field :datanasc %>
  </div>

  <div>
    <%= form.label :genero, style: "display: block" %>
    <%= form.text_field :genero %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg %>
  </div>

  <div>
    <%= form.label :rua, style: "display: block" %>
    <%= form.text_field :rua %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :complemento, style: "display: block" %>
    <%= form.text_field :complemento %>
  </div>

  <div>
    <%= form.label :bairro, style: "display: block" %>
    <%= form.text_field :bairro %>
  </div>

  <div>
    <%= form.label :cidade, style: "display: block" %>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_field :cargo %>
  </div>
  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>
    

  <div>
    <%= form.label :departamento, style: "display: block" %>
    <%= form.text_field :departamento %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/abafuncionarios/edit.html.erb
<% content_for :title, " Editar aba de cadastro  funcionário" %>

<h1>Editar cadastro de funcionário</h1>

<%= render "form", abafuncionario: @abafuncionario %>

<br>

<div>
  <%= link_to "Mostre este cadastro de funcionarios ", @abafuncionario %> |
  <%= link_to "Voltar para lista de cadastro ", abafuncionarios_path %>
</div>

app/views/abafuncionarios/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Cadastre-se</h1>

<div id="abafuncionarios">
  <% @abafuncionarios.each do |abafuncionario| %>
    <%= render abafuncionario %>
    <p>
      <%= link_to "Mostre esse cadastro desse funcionario", abafuncionario %>
    </p>
   <a href="http://127.0.0.1:5500/projeto/app/views/direcao.html" target="_blank">
    Ir para pagina de direcionamento!
 </a>
  <% end %>

</div>
 
<%= link_to "Novo cadastro ", new_abafuncionario_path %>

app/views/abafuncionarios/new.html.erb
<% content_for :title, "Novo cadastro de funcionario " %>
<h1>Cadastro de funcionarios</h1>
<br>
<p>Se cadastre no nosso sistema :)</p>
<br>
<%= render "form", abafuncionario: @abafuncionario %>

<br>

<div>
  <%= link_to "Voltar para cadastro de funcionario", abafuncionarios_path %>
</div>

app/views/abafuncionarios/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @abafuncionario %>

<div>
  <%= link_to "Editar este cadastro desse funcionário", edit_abafuncionario_path(@abafuncionario) %> |
  <%= link_to "voltar para aba de funcionarios", abafuncionarios_path %>

  <%= button_to "Exclua este cadastro do funcionário", @abafuncionario, method: :delete %>
</div>

app/views/cargos/_cargo.html.erb
<div id="<%= dom_id cargo %>">
  <p>
    <strong>Nomecargo:</strong>
    <%= cargo.nomecargo %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= cargo.descricao %>
  </p>

  <p>
    <strong>Departamento:</strong>
    <%= cargo.departamento %>
  </p>

  <p>
    <strong>Nivelcargo:</strong>
    <%= cargo.nivelcargo %>
  </p>

  <p>
    <strong>Salbase:</strong>
    <%= cargo.salbase %>
  </p>

  <p>
    <strong>Requisitos:</strong>
    <%= cargo.requisitos %>
  </p>

  <p>
    <strong>Beneficios:</strong>
    <%= cargo.beneficios %>
  </p>

  <p>
    <strong>Statuscargo:</strong>
    <%= cargo.statuscargo %>
  </p>

</div>

app/views/cargos/_form.html.erb
<%= form_with(model: cargo) do |form| %>
  <% if cargo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cargo.errors.count, "error") %> proibiu que esta carga fosse salva:</h2>

      <ul>
        <% cargo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nomecargo, style: "display: block" %>
    <%= form.text_field :nomecargo %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :departamento, style: "display: block" %>
    <%= form.text_field :departamento %>
  </div>

  <div>
    <%= form.label :nivelcargo, style: "display: block" %>
    <%= form.text_field :nivelcargo %>
  </div>

  <div>
    <%= form.label :salbase, style: "display: block" %>
    <%= form.text_field :salbase %>
  </div>

  <div>
    <%= form.label :requisitos, style: "display: block" %>
    <%= form.text_area :requisitos %>
  </div>

  <div>
    <%= form.label :beneficios, style: "display: block" %>
    <%= form.text_area :beneficios %>
  </div>

  <div>
    <%= form.label :statuscargo, style: "display: block" %>
    <%= form.text_field :statuscargo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<% content_for :title, "Edite este cargo" %>

<h1>Editar cargo</h1>

<%= render "form", cargo: @cargo %>

<br>

<div>
  <%= link_to "Mostre esse cargo", @cargo %> |
  <%= link_to "voltar", cargos_path %>
</div>

app/views/cargos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cargos" %>

<h1>Cargos</h1>

<div id="cargos">
  <% @cargos.each do |cargo| %>
    <%= render cargo %>
    <p>
      <%= link_to "Mostrar esta cargo", cargo %>
    </p>
  <% end %>
</div>

<%= link_to " Cadastrar novo cargo", new_cargo_path %>

app/views/cargos/new.html.erb
<% content_for :title, "novo cargo" %>

<h1>Cadastrar novo cargo</h1>

<%= render "form", cargo: @cargo %>

<br>

<div>
  <%= link_to "voltar para pagina anterior ", cargos_path %>
</div>

app/views/cargos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cargo %>

<div>
  <%= link_to "Editar esse cargo", edit_cargo_path(@cargo) %> |
  <%= link_to "voltar para cargos", cargos_path %>

  <%= button_to "exclua esse cargo", @cargo, method: :delete %>
</div>

app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>">
  <p>
    <strong>Nomedepartamento:</strong>
    <%= departamento.nomedepartamento %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= departamento.descricao %>
  </p>

  <p>
    <strong>Codigodep:</strong>
    <%= departamento.codigodep %>
  </p>

  <p>
    <strong>Localizacao:</strong>
    <%= departamento.localizacao %>
  </p>

  <p>
    <strong>String:</strong>
    <%= departamento.string %>
  </p>

  <p>
    <strong>Statusdep:</strong>
    <%= departamento.statusdep %>
  </p>

</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> proibiu que este departamento fosse salvo:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nomedepartamento, style: "display: block" %>
    <%= form.text_field :nomedepartamento %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :codigodep, style: "display: block" %>
    <%= form.text_field :codigodep %>
  </div>

  <div>
    <%= form.label :localizacao, style: "display: block" %>
    <%= form.text_field :localizacao %>
  </div>

  <div>
    <%= form.label :string, style: "display: block" %>
    <%= form.text_field :string %>
  </div>

  <div>
    <%= form.label :statusdep, style: "display: block" %>
    <%= form.text_field :statusdep %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<% content_for :title, "Edite esse departamento" %>

<h1>Editar departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Mostre essa aba de departamentos ", @departamento %> |
  <%= link_to "Volte para aba departamentos", departamentos_path %>
</div>

app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Departamentos" %>

<h1>Departamentos</h1>

<div id="departamentos">
  <% @departamentos.each do |departamento| %>
    <%= render departamento %>
    <p>
      <%= link_to "Mostre este departamento", departamento %>
    </p>
  <% end %>
</div>

<%= link_to "Novo departamento", new_departamento_path %>

app/views/departamentos/new.html.erb
<% content_for :title, "cadastro departamento" %>

<h1>Novo departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Volte para o cadastro de departamentoos", departamentos_path %>
</div>

app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departamento %>

<div>
  <%= link_to "Editar este departamento", edit_departamento_path(@departamento) %> |
  <%= link_to "voltar para departamentos", departamentos_path %>

  <%= button_to "excluir esse departamento", @departamento, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Projeto" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
 <body>


    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>